# Generated by Django 4.0.1 on 2022-01-27 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_pictures', models.ImageField(upload_to='images/')),
                ('product_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='productApp.productdetails')),
            ],
        ),
    ]
