# Generated by Django 4.0.1 on 2022-01-28 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0003_alter_productdetails_product_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductDetails',
            new_name='ProductDetail',
        ),
    ]
