# Generated by Django 4.0.1 on 2022-01-28 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0004_rename_productdetails_productdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetail',
            name='product_description',
            field=models.CharField(default='', max_length=200),
        ),
    ]
