# Generated by Django 4.0.1 on 2022-01-31 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0005_alter_productdetail_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimages',
            name='product_id',
        ),
        migrations.DeleteModel(
            name='ProductDetail',
        ),
        migrations.DeleteModel(
            name='ProductImages',
        ),
    ]
