# Generated by Django 4.0.1 on 2022-02-02 05:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('productApp', '0006_remove_productimages_product_id_delete_productdetail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UiidModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uiid_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('user_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
