# Generated by Django 4.0.1 on 2022-01-28 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='', max_length=200)),
                ('product_price', models.CharField(default='', max_length=200)),
                ('product_description', models.CharField(default='', max_length=200)),
                ('product_image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_pictures', models.ImageField(upload_to='images/')),
                ('product_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='dashboardApp.productdetail')),
            ],
        ),
    ]
