# Generated by Django 4.0.1 on 2022-01-31 11:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetail',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='product_description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='product_price',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100000, 'Way over %(limit_value)s.')]),
        ),
    ]
