# Generated by Django 4.0.1 on 2022-02-01 06:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardApp', '0002_productdetail_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetail',
            name='time_left',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(20, 'Way over %(limit_value)s.')]),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='total_buyers',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(20, 'Way over %(limit_value)s.')]),
        ),
    ]
