# Generated by Django 4.0.1 on 2022-02-01 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardApp', '0003_productdetail_time_left_productdetail_total_buyers'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetail',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
